### ISSUE TITLE
Cannot find module happy-wrapper

### ISSUE THREAD

**Issue by LarchLiu** [antfu/vite-plugin-md#101]
I got this error when I upgraded vite-plugin-md to 0.17.x in my vitesse project.
```
failed to load config from /Users/xxx/Work/Vue/vitesse/vite.config.ts
error when starting dev server:
Error: Cannot find module '/Users/xxx/Work/Vue/vitesse/node_modules/.pnpm/vite-plugin-md@0.17.4_wie7zz22o3tz6qyv6muewmoury/node_modules/@yankeeinlondon/happy-wrapper/dist/index.cjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/xxx/Work/Vue/vitesse/node_modules/.pnpm/vite-plugin-md@0.17.4_wie7zz22o3tz6qyv6muewmoury/node_modules/vite-plugin-md/dist/index.js:11869:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

Steps:
1. clone [vitesse](https://github.com/antfu/vitesse)
2. upgrade vite-plugin-md to 0.16.x or 0.17.x
3. run pnpm dev

[reproduction](https://codesandbox.io/s/infallible-booth-w9owwt?file=/package.json)

**Comment by vernaillen** [comment]
Same problem here.  I think the issue exists since version 2.2.0 of happy-wrapper.

My project builds and runs again after fixing the version to 2.1.0:
`pnpm add -D @yankeeinlondon/happy-wrapper@2.1.0`

**Comment by kecrily** [comment]
You can set `"type": "module"` in `package.json`

**Comment by flahol** [comment]
Same problem here. thanks to @vernaillen for the solution

**Comment by Codermar** [comment]
Same issue here starting with updating vite-plugin-md > 16 even with adding the type module prop to package.json
```
failed to load config from /usr/local/playground/@codermar/monorepo/marynela.com/vite.config.ts
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'markdown-it' imported from /usr/local/playground/@codermar/monorepo/marynela.com/node_modules/.pnpm/vite-plugin-md@0.17.4_vite@2.9.12+vue@3.2.37/node_modules/vite-plugin-md/dist/index.mjs
    at new NodeError (node:internal/errors:388:5)
    at packageResolve (node:internal/modules/esm/resolve:910:9)
    at moduleResolve (node:internal/modules/esm/resolve:959:20)
    at defaultResolve (node:internal/modules/esm/resolve:1174:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by LarchLiu** [comment]
> Same problem here. I think the issue exists since version 2.2.0 of happy-wrapper.
> 
> My project builds and runs again after fixing the version to 2.1.0: `pnpm add -D @yankeeinlondon/happy-wrapper@2.1.0`

@yankeeinlondon Looks like that's the problem.

**Comment by kecrily** [comment]
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'markdown-it' imported from /usr/local/playground/@codermar/monorepo/marynela.com/node_modules/.pnpm/vite-plugin-md@0.17.4_vite@2.9.12+vue@3.2.37/node_modules/vite-plugin-md/dist/index.mjs

@Codermar Now `markdown-it` is a `peerDependencies`, so you need install it in your project.

```json
"peerDependencies": {
  "vite": "^2.9.9",
  "markdown-it": "^13.0.1"
},
```

**Comment by yankeeinlondon** [comment]
Hi folks, sorry been trying to ensure that everything is ESM and CJS compliant and I think there were a few bumps. 

For context, I'm trying to make sure that the dependency stack works for ESM fully (it has not in the past) and there are a few packages which Vite seems to take issue with:

- `fp-ts` - it has an ESM implementation but the way it's done is awkward and Vite doesn't work well with it so I've made the use of this dependency explicit and rolled and shaken into the actual `vite-plugin-md`; adds a tiny bit to the bundle size but it just works this way so worth the additional payload
- `markdown-it` - it has no ESM implementation (if I remember correctly) so I've pushed it into being a top-level dependency of consumers by making it a peer dependency. Being a top-level dependency allows the bundler to consume the CJS and convert to ESM if the consumer is using ESM (and leave it as-is if consumer is CJS). 

With `happy-wrapper` there is yet another issue with ESM ... and that isn't directly to do with `happy-wrapper` but the `happy-dom` implementation which Vite can handle when a top level dependency but not otherwise. I'm not sure I have fully understood this yet but I had thought by making `happy-wrapper` an ESM export only that I might be able to avoid this.  Based on the issues folks are having though I can see there's a little more tuning to be done.

Sorry for the inconvenience. ESM will be a great world once we're finally there but the journey has a lot of little potholes along it.

**Comment by yankeeinlondon** [comment]
Can someone please check that `v0.18.1` fixes this problem? In my tests it does.

**Comment by kecrily** [comment]
It's fine for me

**Comment by LarchLiu** [comment]
@yankeeinlondon 🎉 It works, thanks!

fixed @0.18.1
